### ISSUE TITLE
Failed inside SetShapeProperties

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#11]
armyc2.c2sd.JavaTacticalRenderer.clUtility.SetShapeProperties line 1246
armyc2.c2sd.JavaRendererServer.ReaderMultipoints.clsRenderer2.GetLineArray line 346

I'm getting this error a number of times when panning/zooming. Unfortunately, the stack trace doesn't help too much, not sure what's going on. This is using SECRenderer.RenderSymbol

**Comment by mdeutch3** [comment]
If you could provide the set of parameters you are using to get the error that would be helpful.

**Comment by spyhunter99** [comment]
here's two examples. I think it's actually rendering and this trace is more of a warning anything else but I'm not sure. Both are via SECWebRenderer.RenderSymbol.


I/a       (13649): render multipoint KML with  attrib:1 mods:4 font:18 id=252f1392-9bd2-44b8-9410-42b5dce7f2f3 name= code=GFGPOLAGM---USX points=9.12783598820437,36.6779813479612 8
.70099444178175,36.4961096392347 8.72573899344377,36.5827151509566  altmode=relativeToGround scale=195165.0 bbox=6.416015,36.829073,9.052734,38.136716
D/a       (13649): Line Color not defined
D/a       (13649): Fill Color not defined
D/a       (13649): Font Size not defined
D/a       (13649): Pixel Size not defined
D/a       (13649): Scale not defined
D/a       (13649): Keep Unit Ratio not defined
D/a       (13649): Alpha not defined
D/a       (13649): Outline Symbol not defined
D/a       (13649): Outline Color not defined
D/a       (13649): Draw as icon not defined
D/a       (13649): Symbology Standard not defined
D/a       (13649): Quantity not defined
D/a       (13649): Additional Info 1
D/a       (13649): Additional Info 2
D/a       (13649): Additional Info 3 not defined
D/a       (13649): Hostile not defined
D/a       (13649): Direction of movement not defined
D/a       (13649): Unique Designation 1
D/a       (13649): Unique Designation 2
D/a       (13649): Equipment Type not defined
D/a       (13649): DTG not defined
D/a       (13649): DTG not defined
D/a       (13649): Altitude or depth not defined
D/a       (13649): Location not defined
D/a       (13649): Distance not defined
D/a       (13649): Azimuth not defined
D/a       (13649): Length not defined
D/a       (13649): Width not defined
D/a       (13649): Radius not defined
D/a       (13649): Angle not defined
E/clsUtility.SetShapeProperties(13649): May 03, 2015 08:26:34 AM clsUtility.SetShapeProperties
E/clsUtility.SetShapeProperties(13649): INFO: Failed inside SetShapeProperties
E/clsUtility.SetShapeProperties(13649): armyc2.c2sd.renderer.utilities.RendererException: Failed inside SetShapeProperties
E/clsUtility.SetShapeProperties(13649):         at armyc2.c2sd.JavaTacticalRenderer.clsUtility.SetShapeProperties(SourceFile:1246)
E/clsUtility.SetShapeProperties(13649):         at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer2.GetLineArray(SourceFile:346)
E/clsUtility.SetShapeProperties(13649):         at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer.render_GE(SourceFile:1146)
E/clsUtility.SetShapeProperties(13649):         at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer.renderWithPolylines(SourceFile:957)



I/a       (13649): render multipoint KML with  attrib:1 mods:4 font:18 id=0bace5c1-6047-4b73-b542-4c27cc608434 name= code=GPGPOLAV------X points=8.38200535818297,37.7911627989274 9
.02289087231853,37.5967194088932 8.97777997230298,37.6293858648913  altmode=relativeToGround scale=789850.0 bbox=6.086425,33.742612,16.6333,39.044786
D/a       (13649): Line Color not defined
D/a       (13649): Fill Color not defined
D/a       (13649): Font Size not defined
D/a       (13649): Pixel Size not defined
D/a       (13649): Scale not defined
D/a       (13649): Keep Unit Ratio not defined
D/a       (13649): Alpha not defined
D/a       (13649): Outline Symbol not defined
D/a       (13649): Outline Color not defined
D/a       (13649): Draw as icon not defined
D/a       (13649): Symbology Standard not defined
D/a       (13649): Quantity not defined
D/a       (13649): Additional Info 1
D/a       (13649): Additional Info 2
D/a       (13649): Additional Info 3 not defined
D/a       (13649): Hostile not defined
D/a       (13649): Direction of movement not defined
D/a       (13649): Unique Designation 1
D/a       (13649): Unique Designation 2
D/a       (13649): Equipment Type not defined
D/a       (13649): DTG not defined
D/a       (13649): DTG not defined
D/a       (13649): Altitude or depth not defined
D/a       (13649): Location not defined
D/a       (13649): Distance not defined
D/a       (13649): Azimuth not defined
D/a       (13649): Length not defined
D/a       (13649): Width not defined
D/a       (13649): Radius not defined
D/a       (13649): Angle not defined
E/clsUtility.SetShapeProperties(13649): May 03, 2015 08:31:45 AM clsUtility.SetShapeProperties
E/clsUtility.SetShapeProperties(13649): INFO: Failed inside SetShapeProperties
E/clsUtility.SetShapeProperties(13649): armyc2.c2sd.renderer.utilities.RendererException: Failed inside SetShapeProperties
E/clsUtility.SetShapeProperties(13649):         at armyc2.c2sd.JavaTacticalRenderer.clsUtility.SetShapeProperties(SourceFile:1246)
E/clsUtility.SetShapeProperties(13649):         at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer2.GetLineArray(SourceFile:346)
E/clsUtility.SetShapeProperties(13649):         at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer.render_GE(SourceFile:1146)
E/clsUtility.SetShapeProperties(13649):         at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer.renderWithPolylines(SourceFile:957)

**Comment by mdeutch3** [comment]
A logic error in SetShapeProperties has been fixed. The change has been checked in. The loop iterator was not accounting for whether the shapes array had been resized.

**Comment by michael-spinelli** [comment]
Fixed, will be available in next release (.56)
