### ISSUE TITLE
Attempt to invoke virtual mentod 'int java.util.ArrayList.size()' on  a null object reference

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#12]
I got this message when panning/zooming on using bounding box, screen height/width calling SECRenderer.RenderSymbol2D.

Symbol code was GFGPSAO-------X

The returned KML actually contained the error message and no stack trace was available

**Comment by michael-spinelli** [comment]
I was incorrect when I told you RenderSymbol2D was fully implemented. When it's working, I'll note it here and in the related release.

**Comment by mdeutch3** [comment]
RenderSymbol2D fixes for KML and GeoJSON format have been checked in.

**Comment by mdeutch3** [comment]
Fixes for GeoJSON format for RenderSymbol and RenderSymbol2D have been checked in.

**Comment by michael-spinelli** [comment]
fixed in release .58
