### ISSUE TITLE
Failed inside clsClipPolygon2.ClipPolygon

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#13]
armyc2.c2sd.JavaRendererServer.ReaderMultipoints.clsClipPolygon2.ClipPolygon line 855
armyc2.c2sd.JavaRendererServer.ReaderMultipoints.clsRenderer.reader_GE line 1083
armyc2.c2sd.JavaRendererServer.ReaderMultipoints.clsRenderer.readerWithPolylines line 957

i think this was with render 2D

symbol code was GFMPSP-----F--X

**Comment by mdeutch3** [comment]
Which function are you calling? Is it RenderSymbol2D? That function currently isn’t fully implemented. It does not call clsRenderer.render_GE and does not not reach JavaRendererServer code.

**Comment by spyhunter99** [comment]
Correction, this is with SecWebRenderer.RenderSymbol. 

The "2D" version doesn't render and of the lines for some reason using the same inputs + screen pixels (for anything in my case), separate issue

**Comment by spyhunter99** [comment]
here's a trace to help

I/a       (15438): render multipoint KML with  attrib:1 mods:8 font:18 id=d31d3c34-4045-4fa4-8477-3c00f9b331c0 name=ANamedItem code=GHGPPY--------X points=133.93718930040794,32.
92804222360567  altmode=relativeToGround scale=23575.0 bbox=-74.74514,39.881025,-74.41555,40.038917
D/a       (15438): Line Color not defined
D/a       (15438): Fill Color not defined
D/a       (15438): Font Size not defined
D/a       (15438): Pixel Size not defined
D/a       (15438): Scale not defined
D/a       (15438): Keep Unit Ratio not defined
D/a       (15438): Alpha not defined
D/a       (15438): Outline Symbol not defined
D/a       (15438): Outline Color not defined
D/a       (15438): Draw as icon not defined
D/a       (15438): Symbology Standard not defined
D/a       (15438): Quantity not defined
D/a       (15438): Additional Info 1 Additional Info H012
D/a       (15438): Additional Info 2 Additional Info_H1_2
D/a       (15438): Additional Info 3 Additional Info H2_2
D/a       (15438): Hostile not defined
D/a       (15438): Direction of movement 120.0
D/a       (15438): Unique Designation 1 Unique DesignattionT 01234567890123
D/a       (15438): Unique Designation 2 Unique DesignattionT1 0123456789012
D/a       (15438): Equipment Type not defined
D/a       (15438): DTG 2015-05-03T09:11:22-0400
D/a       (15438): DTG 2015-05-03T09:15:22-0400
D/a       (15438): Altitude or depth not defined
D/a       (15438): Location not defined
D/a       (15438): Distance not defined
D/a       (15438): Azimuth not defined
D/a       (15438): Length not defined
D/a       (15438): Width not defined
D/a       (15438): Radius not defined
D/a       (15438): Angle not defined
E/clsClipPolygon2.ClipPolygon(15438): May 03, 2015 09:37:29 AM clsClipPolygon2.ClipPolygon
E/clsClipPolygon2.ClipPolygon(15438): INFO: Failed inside ClipPolygon
E/clsClipPolygon2.ClipPolygon(15438): armyc2.c2sd.renderer.utilities.RendererException: Failed inside ClipPolygon
E/clsClipPolygon2.ClipPolygon(15438):         at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsClipPolygon2.ClipPolygon(SourceFile:855)
E/clsClipPolygon2.ClipPolygon(15438):         at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer.render_GE(SourceFile:1083)
E/clsClipPolygon2.ClipPolygon(15438):         at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer.renderWithPolylines(SourceFile:957)

**Comment by mdeutch3** [comment]
DMAF requires 3 points minimum. It should fail canRenderMultipoint and return a message indicating 3 points minimum required. But canRenderMultiPoint was not implemented. It has been implemented. Change has been checked in.

**Comment by mdeutch3** [comment]
A change was checked in. RenderSymbol2D does render but it only works for KML format.

**Comment by spyhunter99** [comment]
sorry, what's DMAF stand for?

**Comment by mdeutch3** [comment]
Decoy Mined Area, Fenced: G*GPPY---------

**Comment by michael-spinelli** [comment]
Fixed, will be available in next release (.56)
