### ISSUE TITLE
Sending a named color as fill or line color causes NPE

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#15]
If you pass in something like "black" or "cyan" as a fill color, a NPE is thrown at Color.toARGB. I understand that this problem is really on my end, but throwing a NPE could handled better. Perhaps log a warning or something

**Comment by michael-spinelli** [comment]
singlepoints or multipoints?

**Comment by michael-spinelli** [comment]
Fixed, no more NPEs, bad colors will go black.
