### ISSUE TITLE
Feature request: font color and font background color fill support

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#16]
It would be nice if we could support filling the background color of fonts, as well as the font color selection

**Comment by michael-spinelli** [comment]
Do you mean like a a colored rectangle behind the label instead of just an outline?

**Comment by spyhunter99** [comment]
Yes

**Comment by michael-spinelli** [comment]
You want to set the color across the board or on a per symbol basis like line color?

**Comment by spyhunter99** [comment]
Per symbol basis

**Comment by michael-spinelli** [comment]
Set the textBackgroundMethod in RendererSettings.
RendererSettings.TextBackgroundMethod_NONE/COLORFILL/OUTLINE

MilStdAttributes also now has TextColor and TextBackgroundColor

Will be available in release .59
