### ISSUE TITLE
large memory allocation for relatively small images?

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#17]
using the jdk version of the renderer, i've confirmed that the output of the following icon is about 4KB however (due to various issues) I'm getting OOM exceptions on ADK. The strange part is the error message

So i'm not entirely sure what the root cause is. In either case 1/2 MB allocation for a small icon seems strange.

E/art     (20136): Throwing OutOfMemoryError "Failed to allocate a 501276 byte allocation with 8530192 free bytes"
W/System.err(20136): java.lang.OutOfMemoryError: Failed to allocate a 501276 byte allocation with 8530192 free bytes
W/System.err(20136):    at android.graphics.Bitmap.nativeCreate(Native Method)
W/System.err(20136):    at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
W/System.err(20136):    at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
W/System.err(20136):    at android.graphics.Bitmap.createBitmap(Bitmap.java:754)
W/System.err(20136):    at armyc2.c2sd.renderer.TacticalGraphicIconRenderer.getIcon(SourceFile:71)
W/System.err(20136):    at armyc2.c2sd.renderer.MilStdIconRenderer.renderTacticalMultipointIcon(SourceFile:278)
W/System.err(20136):    at armyc2.c2sd.renderer.MilStdIconRenderer.RenderIcon(SourceFile:314)
W/System.err(20136): OOM! Error rendering symbol: Symbol Code: GFGPGLB----J--X
D/a       (20136): Line Color 000000
D/a       (20136): Fill Color 00ffff
D/a       (20136): Font Size not defined
D/a       (20136): Pixel Size 354
D/a       (20136): Scale not defined
D/a       (20136): Keep Unit Ratio not defined
D/a       (20136): Alpha not defined
D/a       (20136): Outline Symbol not defined
D/a       (20136): Outline Color 000000
D/a       (20136): Draw as icon not defined
D/a       (20136): Symbology Standard 1
D/a       (20136): Quantity not defined
D/a       (20136): Additional Info 1 not defined
D/a       (20136): Additional Info 2 0.00000000
D/a       (20136): Additional Info 3 not defined
D/a       (20136): Hostile not defined
D/a       (20136): Direction of movement not defined
D/a       (20136): Unique Designation 1 TCORPS_1013
D/a       (20136): Unique Designation 2 T1t1t1t1t1
D/a       (20136): Equipment Type not defined
D/a       (20136): DTG 2015-05-03T09:16:58-0400
D/a       (20136): DTG 2015-05-03T09:20:58-0400
D/a       (20136): Altitude or depth not defined
D/a       (20136): Location not defined
D/a       (20136): Distance not defined
D/a       (20136): Azimuth not defined
D/a       (20136): Length not defined
D/a       (20136): Width not defined
D/a       (20136): Radius not defined
D/a       (20136): Angle not defined

Here's a 'S' icon, same deal

W/System.err(20136):    at android.graphics.Bitmap.nativeCreate(Native Method)
W/System.err(20136):    at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
W/System.err(20136):    at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
W/System.err(20136):    at android.graphics.Bitmap.createBitmap(Bitmap.java:754)
W/System.err(20136):    at armyc2.c2sd.renderer.SinglePointRenderer.RenderUnit(SourceFile:319)
W/System.err(20136):    at armyc2.c2sd.renderer.MilStdIconRenderer.RenderIcon(SourceFile:325)

W/System.err(20136): OOM! Error rendering symbol: Symbol Code: SFGPUCFH--AD---
D/a       (20136): Line Color not defined
D/a       (20136): Fill Color not defined
D/a       (20136): Font Size not defined
D/a       (20136): Pixel Size 354
D/a       (20136): Scale not defined
D/a       (20136): Keep Unit Ratio not defined
D/a       (20136): Alpha not defined
D/a       (20136): Outline Symbol not defined
D/a       (20136): Outline Color not defined
D/a       (20136): Draw as icon not defined
D/a       (20136): Symbology Standard 1
D/a       (20136): Quantity not defined
D/a       (20136): Reinforced Reduced not defined
D/a       (20136): Staff Comments not defined
D/a       (20136): Additional Info 1 not defined
D/a       (20136): Additional Info 2 not defined
D/a       (20136): Additional Info 3 not defined
D/a       (20136): Evaluation Rating not defined
D/a       (20136): Combat Effectiveness not defined
D/a       (20136): Signature Equip not defined
D/a       (20136): Higher Formation not defined
D/a       (20136): Hostile not defined
D/a       (20136): IFF SIF not defined
D/a       (20136): Direction of Movement not defined
D/a       (20136): SIGNIT Mobility Indicator not defined
D/a       (20136): Unique Designation 1 01234567
D/a       (20136): Unique Designation 2 not defined
D/a       (20136): Equip Type not defined
D/a       (20136): DTG 1 not defined
D/a       (20136): DTG 2 not defined
D/a       (20136): Altitude Depth not defined
D/a       (20136): Location not defined
D/a       (20136): Speed not defined
D/a       (20136): Special C2 HQ not defined
D/a       (20136): Platform Type not defined
D/a       (20136): Equipment Teardown Time not defined
D/a       (20136): Common Identifier not defined
D/a       (20136): Aux Equip Indicator not defined
D/a       (20136): Area of Uncertainty not defined
D/a       (20136): Dead Reckoning Trailer not defined
D/a       (20136): Speed Leader not defined
D/a       (20136): Pairing Line not defined
D/a       (20136): Engagement Bar not defined

**Comment by michael-spinelli** [comment]
Made some improvements.  Will be in .58 release.

**Comment by michael-spinelli** [comment]
Reworked the image cache.  Should no longer run into memory issues as of release .62

Also, user can now set the cache size as a percentage of the max size of the VM heap:
RenderSettings.getInstance().setCacheSize(float percentage)//like 0.05f for 5%

OR

the user can specify the cache size in bytes setCacheSize(int bytes)

Default cache size is 5% of the VM heap
