### ISSUE TITLE
WO-DMPA----L---- Pipelines/pipe renders as area, not a line

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#19]

**Comment by mdeutch3** [comment]
Can you provide the function and parameters? I'm unable to produce the error.

**Comment by spyhunter99** [comment]
SECRenderer.RenderSymbol. i'll get you the rest of the info soon

**Comment by spyhunter99** [comment]
I/RendererService(13196): render multipoint KML with  attrib:1 mods:0 font:18 id=c968427e-ffc2-458e-b07e-3174ecfd58d5 name=Default Layer code=WO-DMPA----L--- points=-75.083656,41.405398 -75.082283,41.397672 -75.047264,41.344082 -74.95388,41.373201 -74.93328,41.394582 -75.083656,41.405398  altmode=relativeToGround scale=51640.0 bbox=-75.38166,41.144277,-74.502754,41.556637

**Comment by mdeutch3** [comment]
It appears the 0th point is identical to the nth point, in which case it will appear to render as an area because you’ve closed the line.

**Comment by spyhunter99** [comment]
ahh problem was on my end. sorry about that
