### ISSUE TITLE
Multipoint reneder generates color codes that are invalid

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#2]
I'm getting a number of color codes in the resultant kml file that looks like "x196964096". Color codes can only be AARRGGBB which is 8 chars. The output was 9 chars. I've also got a few that were 7 chars like "x1409696"

**Comment by michael-spinelli** [comment]
Are you setting a line color or are you getting weird values with just the default colors the renderer sets?  Can you send me the inputs and your resultant kml?

**Comment by spyhunter99** [comment]
the input doesn't specify any colors, modifiers or attributes. no idea what's happening
here's the output
<Folder id="1382647a-81df-48b3-9e93-8fd8a652dc92">
	<name>
		<![CDATA[PAA3]]>
	</name>
	<visibility>1</visibility>
	<Placemark>
		<description>
			<![CDATA[<b>PAA3</b><br/>]]></description>
		<Style id="lineColor">
			<LineStyle>
				<color>ff000000</color>
				<colorMode>normal</colorMode>
				<width>3</width>
			</LineStyle>
		</Style>
		<MultiGeometry>
			<LineString>
				<tessellate>1</tessellate>
				<altitudeMode>clampToGround</altitudeMode>
				<coordinates>-74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 </coordinates>
			</LineString>
		</MultiGeometry>
	</Placemark>
	<Placemark>
		<name>
			<![CDATA[PAA]]>
		</name>
		<Style>
			<IconStyle>
				<scale>.7</scale>
				<heading>0</heading>
				<Icon>
					<href/>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>x196964096</color>
				<scale>.8</scale>
			</LabelStyle>
		</Style>
		<Point>
			<extrude>1</extrude>
			<altitudeMode>relativeToGround</altitudeMode>
			<coordinates>-74.52637795,40.01043651</coordinates>
		</Point>
	</Placemark>
	<Placemark>
		<name>
			<![CDATA[PAA]]>
		</name>
		<Style>
			<IconStyle>
				<scale>.7</scale>
				<heading>0</heading>
				<Icon>
					<href/>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>x196964096</color>
				<scale>.8</scale>
			</LabelStyle>
		</Style>
		<Point>
			<extrude>1</extrude>
			<altitudeMode>relativeToGround</altitudeMode>
			<coordinates>-74.52637795,40.01043651</coordinates>
		</Point>
	</Placemark>
	<Placemark>
		<name>
			<![CDATA[PAA]]>
		</name>
		<Style>
			<IconStyle>
				<scale>.7</scale>
				<heading>0</heading>
				<Icon>
					<href/>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>x196964096</color>
				<scale>.8</scale>
			</LabelStyle>
		</Style>
		<Point>
			<extrude>1</extrude>
			<altitudeMode>relativeToGround</altitudeMode>
			<coordinates>-74.52637795,40.01043651</coordinates>
		</Point>
	</Placemark>
	<Placemark>
		<name>
			<![CDATA[PAA]]>
		</name>
		<Style>
			<IconStyle>
				<scale>.7</scale>
				<heading>0</heading>
				<Icon>
					<href/>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>x196964096</color>
				<scale>.8</scale>
			</LabelStyle>
		</Style>
		<Point>
			<extrude>1</extrude>
			<altitudeMode>relativeToGround</altitudeMode>
			<coordinates>-74.52637795,40.01043651</coordinates>
		</Point>
	</Placemark>
</Folder>

**Comment by michael-spinelli** [comment]
ok, bad color  values are in the labels.  I believe I see the problem.

**Comment by michael-spinelli** [comment]
Fix checked in.  You'll see it in the next release.  .49 probably.

**Comment by spyhunter99** [comment]
awesome, thanks for the quick turn around!
