### ISSUE TITLE
failed inside set_SymbolId for GFGPPGLP-----USX phase line

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#20]
I/RendererService( 8529): render multipoint KML with  attrib:1 mods:10 font:18 id=7a0b13e8-4451-4ca0-bbc3-6b3d34be3dea name=GFGPPGLP-----USX code=GFGPPGLP-----USX points=-74.557017
00190251,40.00866618362844 -74.52169991373249,39.95990792636891  altmode=relativeToGround scale=13190.0 bbox=-74.641113,39.857046,-74.421386,39.962385
E/TGLight.set_SymbolId( 8529): May 08, 2015 06:49:12 PM TGLight.set_SymbolId
E/TGLight.set_SymbolId( 8529): INFO: Failed inside set_SymbolId
E/TGLight.set_SymbolId( 8529): armyc2.c2sd.renderer.utilities.RendererException: Failed inside set_SymbolId
E/TGLight.set_SymbolId( 8529):         at armyc2.c2sd.JavaTacticalRenderer.TGLight.set_SymbolId(TGLight.java:441)
E/TGLight.set_SymbolId( 8529):         at sec.web.render.MultiPointHandler.RenderSymbol(MultiPointHandler.java:691)
E/TGLight.set_SymbolId( 8529):         at sec.web.render.SECWebRenderer.RenderSymbol(SECWebRenderer.java:322)
E/TGLight.set_SymbolId( 8529):         at 

W/System.err( 8529): render failed! 7a0b13e8-4451-4ca0-bbc3-6b3d34be3dea,GFGPPGLP-----USX,None,GFGPPGLP-----USX,-74.55701700190251,40.00866618362844 -74.52169991373249,39.959907926
36891 ,relativeToGround,13190.0,-74.641113,39.857046,-74.421386,39.962385,{2=0, 3=, 4=, 5=, 7=0.0, 9=700005, 10=700005, 12=2001-12-17T09:30:47Z, 13=2001-12-17T09:30:47Z, 14=0},{13=
false, 14=AGL}0,1
D/RendererService( 8529): Line Color not defined
D/RendererService( 8529): Fill Color not defined
D/RendererService( 8529): Font Size not defined
D/RendererService( 8529): Pixel Size not defined
D/RendererService( 8529): Scale not defined
D/RendererService( 8529): Keep Unit Ratio not defined
D/RendererService( 8529): Alpha not defined
D/RendererService( 8529): Outline Symbol not defined
D/RendererService( 8529): Outline Color not defined
D/RendererService( 8529): Draw as icon not defined
D/RendererService( 8529): Symbology Standard not defined
D/RendererService( 8529): Quantity 0
D/RendererService( 8529): Additional Info 1
D/RendererService( 8529): Additional Info 2
D/RendererService( 8529): Additional Info 3
D/RendererService( 8529): Hostile not defined
D/RendererService( 8529): Direction of movement 0.0
D/RendererService( 8529): Unique Designation 1 700005
D/RendererService( 8529): Unique Designation 2 700005
D/RendererService( 8529): Equipment Type not defined
D/RendererService( 8529): DTG 2001-12-17T09:30:47Z
D/RendererService( 8529): DTG 2001-12-17T09:30:47Z
D/RendererService( 8529): Altitude or depth 0
D/RendererService( 8529): Location not defined
D/RendererService( 8529): Distance not defined
D/RendererService( 8529): Azimuth not defined
D/RendererService( 8529): Length not defined
D/RendererService( 8529): Width not defined
D/RendererService( 8529): Radius not defined
D/RendererService( 8529): Angle not defined

 {"type":"error","error":"There was an error creating t
he MilStdSymbol GFGPPGLP-----USX: - symbolID: "GFGPPGLP-----USX" not recognized. - "}

**Comment by mdeutch3** [comment]
GFGPPGLP-----USX is not a valid symbol code. Did you intend to use G*GPGLP---****X ?

**Comment by spyhunter99** [comment]
* as defined in the spec, can be any one of the values defined in the table B1, or am I misunderstanding something?

**Comment by mdeutch3** [comment]
It failed because of the symbol code you used, which is 16 characters and isn't in any table. I'm not sure what you're referring to.

**Comment by spyhunter99** [comment]
doh! that fixed it. The bullet point was actually '*', in markdown it's a bullet.
