### ISSUE TITLE
Phase Line label not honored?

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#21]
Maybe i'm doing something wrong, but phase lines with echelon (in the symbol code) doesn't appear to be rendering the appropriate marker on the phase line. Does the echelon need to be passed in as a modifier? I'm passing in
GFGPGLP----H--X as a symbol code

**Comment by mdeutch3** [comment]
The echelon is part of the symbol code and does not get passed as a modifier. I was unable to produce any error with GFGPGLP----H--X as a symbol code. Phase line is not affected by the echelon.

**Comment by spyhunter99** [comment]
Understood. I'm referencing page 468 of milstd2525c and looking at the example with "XX" listed in the break, which is described as an end of line information. Can the renderer produce these?

**Comment by spyhunter99** [comment]
Also for phase line, the "T" block should be the name of the phase line, however all I get the renderer to produce is "PL-PL" as the anchor points. Is there a modifier to support the named anchor point/

**Comment by michael-spinelli** [comment]
The lines with the "XX" you see in the template are actually boundary lines that are being used in conjunctions with the phase line.  

If you're setting the 'T' modifier and it's not being populated where the "T" block is indicated, then that's a bug.  Deutch, can you confirm?

**Comment by mdeutch3** [comment]
The T modifier does display as PL [T] if the modifier is set, e.g. if T is set to NAME then the end of line text would display as PL NAME.

**Comment by spyhunter99** [comment]
Looks like my issue was related to the kml > map engine/parser. Fixed on that end. thanks for looking into it
