### ISSUE TITLE
NPE getIdealOutlineColor

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#22]
in v59

NPE R
RendererUtilities.getIdealoutlineColor line 19
called from armyc2.c2sd.renderer.ModifierRenderer.renderText 3017

symbol code was GFGPOGF------X
lineColor = 00ffff
unique designator 1 = test

**Comment by mdeutch3** [comment]
GFGPOGF------X is 14 characters. Are you sure this is the code you used?

**Comment by spyhunter99** [comment]
sorry probably a typo while swivel chairing
GFGPOGF-------X

**Comment by mdeutch3** [comment]
CanRenderMultiPoint was throwing errors each time. Please try latest.

**Comment by spyhunter99** [comment]
Still crashing. 
armyc2c2sd.renderer.utiloities.RendererUtiloities.getIdealOutlineColor, line 19

This is also throwing for single point icons

**Comment by michael-spinelli** [comment]
New RendererUtilities checked in.  Won't crash anymore.  Still looking into why null color values are being sent in.

**Comment by michael-spinelli** [comment]
fixed: removed bad shape from resultant object.
