### ISSUE TITLE
Error rendering multipoint, ARGBtoABGR 37

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#23]
symbol code 
GFM*OGR---****X
line color 00ffff
ArrayIndexOfOutBounds exception, length=1, index=2 at
sec.web.render.utilities.JavaRendererUtilities.ARGBtoABGR line 37
called from 
MultiPointHandler.ShapeToKMLString  (MultiPointHandler 2547)
KMLize  (MultiPointHandler 2003)
RenderSymbol (MultiPointHandler 738)
RenderSymbol (SECWebRenderer 322)

**Comment by mdeutch3** [comment]
GFMOGR---***X is 13 characters. Are you sure this is the code you used?

**Comment by spyhunter99** [comment]
GFMOGR-----***X swivel chair typo

**Comment by michael-spinelli** [comment]
Fix checked in.  Will be in release .60
