### ISSUE TITLE
Symbol not recognized GFFPACVI------X

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#24]
not sure what i'm doing wrong here. The spec lists this code as
G*F*ACVI--****X
modifiers defined: lineColor as 00ffff

**Comment by spyhunter99** [comment]
I'm getting this with a number of other fire irregular areas, like
GFFPACDI-------
I also tried it with/without the last char being 'X'

**Comment by michael-spinelli** [comment]
Any chance the symbology standard is set to B instead of C?

**Comment by spyhunter99** [comment]
Nope. Ironically, I can get an icon view (DrawAsIcon=true) but it's not rendering the kml

**Comment by spyhunter99** [comment]
im' definitely on 2525C std

**Comment by mdeutch3** [comment]
I'm unable to produce the error using any combination of inputs. Can I get all of the inputs you're using?

**Comment by mdeutch3** [comment]
A fix has been checked in.

**Comment by spyhunter99** [comment]
ok, so you still need the input? sounds like you find the issue

**Comment by mdeutch3** [comment]
I don't need the input. The error was in our code and has been corrected. It should fix the problem for all the fire support areas that are not part of Rev B.
