### ISSUE TITLE
Information warfare icon is rendering with strange symbol

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#26]
SFGPUUI is rendering with a strange symbol, looks like a font in another language

**Comment by spyhunter99** [comment]
also, Signal Support and Landing Support

**Comment by michael-spinelli** [comment]
Updated font indexes.  All glyphs moved to an area call the "Private Use Area" or PUA.  This is where special symbols should live so they do not conflict.  Hopefully this resolves all android issues where the correct glyph doesn't render.  I tested this by looping through and checking the bounds for all rendered characters.  99% of milstd symbology starts left of zero.  regular letters start right of zero.  Going by this test, everything should render correctly from the unitfont.ttf file.  Let me know if you still have issues like this.  I'll be updating the other font files soon and then carry it over to the other ports for consistency.  Code checked in.
