### ISSUE TITLE
G*O*ES----****X renders but isn't in the spec?

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#29]
I've been combing through the milstd and I don't see G*O*ES----****X listed anywhere, however it is listed in the xml that the renderer comes with and it does render as a point graphic with the letters SOS in them. It happens to be what i'm looking for, however i'm a bit puzzled that it's not in the spec. is this an extension or something?

**Comment by michael-spinelli** [comment]
It's Emergency Distress call and is found in the USAS.

USAS COEv1 is for 2525Bch2
USAS COEv2 is for 2525C

These explain and sometimes add to 2525 symbology.  We have a requirement to support USAS.
I've sent you copies of the documents.
