### ISSUE TITLE
Rendering multipoint to kml to outputting too many points

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#3]
I'm passing in 6 pairs of lat,lons and the renderer's kml as the same set close to 100 times!. Not sure what's going on here. Symbol code is GFFPACPC-------

**Comment by michael-spinelli** [comment]
Can you give us the all the inputs you used so we can have your exact scenario?

**Comment by spyhunter99** [comment]
So i've notified that the scale is out of whack, as is the bounding box of the current view. Also the lat/lons are reversed due to a parsing issues with osmbonuspack, otherwise this renders near the south pole instead of NJ

input:
render multipoint KML
id=1382647a-81df-48b3-9e93-8fd8a652dc92 
name=PAA3 
description=test
symbolCode=GFFPACPC------- 
controlPoints=-74.52662519936254,40.01053675723952 -74.52278683768199,40.008169474836585 -74.518204633732,40.00832170095601 -74.51853655875559,40.01110708754908 -74.52552645420761,40.01184768479645 -74.52662519936254,40.01053675723952 
altMode=relativeToGround 
mapscale=529.0 
boundingbox=85.034753,-180.0,85.05112799999999,-179.67041
modifiers=none
attributes=none
0
1


SECWebRenderer.RenderSymbol(uniqueId, name, description, symbolCode, controlPoints, altMode, mapscale, boundingbox, modifiersArray, attributesArray, 0, 1);


output:
<Folder id="1382647a-81df-48b3-9e93-8fd8a652dc92">
	<name>
		<![CDATA[PAA3]]>
	</name>
	<visibility>1</visibility>
	<Placemark>
		<description>
			<![CDATA[<b>PAA3</b><br/>]]></description>
		<Style id="lineColor">
			<LineStyle>
				<color>ff000000</color>
				<colorMode>normal</colorMode>
				<width>3</width>
			</LineStyle>
		</Style>
		<MultiGeometry>
			<LineString>
				<tessellate>1</tessellate>
				<altitudeMode>clampToGround</altitudeMode>
				<coordinates>-74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 -74.52660671,40.01053476 </coordinates>
			</LineString>
		</MultiGeometry>
	</Placemark>
	<Placemark>
		<name>
			<![CDATA[PAA]]>
		</name>
		<Style>
			<IconStyle>
				<scale>.7</scale>
				<heading>0</heading>
				<Icon>
					<href/>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>x196964096</color>
				<scale>.8</scale>
			</LabelStyle>
		</Style>
		<Point>
			<extrude>1</extrude>
			<altitudeMode>relativeToGround</altitudeMode>
			<coordinates>-74.52637795,40.01043651</coordinates>
		</Point>
	</Placemark>
	<Placemark>
		<name>
			<![CDATA[PAA]]>
		</name>
		<Style>
			<IconStyle>
				<scale>.7</scale>
				<heading>0</heading>
				<Icon>
					<href/>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>x196964096</color>
				<scale>.8</scale>
			</LabelStyle>
		</Style>
		<Point>
			<extrude>1</extrude>
			<altitudeMode>relativeToGround</altitudeMode>
			<coordinates>-74.52637795,40.01043651</coordinates>
		</Point>
	</Placemark>
	<Placemark>
		<name>
			<![CDATA[PAA]]>
		</name>
		<Style>
			<IconStyle>
				<scale>.7</scale>
				<heading>0</heading>
				<Icon>
					<href/>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>x196964096</color>
				<scale>.8</scale>
			</LabelStyle>
		</Style>
		<Point>
			<extrude>1</extrude>
			<altitudeMode>relativeToGround</altitudeMode>
			<coordinates>-74.52637795,40.01043651</coordinates>
		</Point>
	</Placemark>
	<Placemark>
		<name>
			<![CDATA[PAA]]>
		</name>
		<Style>
			<IconStyle>
				<scale>.7</scale>
				<heading>0</heading>
				<Icon>
					<href/>
				</Icon>
			</IconStyle>
			<LabelStyle>
				<color>x196964096</color>
				<scale>.8</scale>
			</LabelStyle>
		</Style>
		<Point>
			<extrude>1</extrude>
			<altitudeMode>relativeToGround</altitudeMode>
			<coordinates>-74.52637795,40.01043651</coordinates>
		</Point>
	</Placemark>
</Folder>

**Comment by michael-spinelli** [comment]
Well one problem is you are missing an AM value for the radius of your circular target.
Check [Setting Modifiers](https://github.com/missioncommand/mil-sym-android/wiki#321----setting-modifiers) in the dev guide.  Try adding one and let me know if you still have issues.

    SparseArray<String> modifiers = new SparseArray<String>();  
    modifiers.put(ModifiersTG.AM_DISTANCE,"3000");

**Comment by mdeutch3** [comment]
GFFPACPC------- is the PAA Circular symbol. It takes only one point and a radius in meters, AM[0] as input parameters.

**Comment by spyhunter99** [comment]
that did it! thanks
