### ISSUE TITLE
documentation on BS_ and BBS_ symbol codes

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#31]
Looking at the source, it looks like there's some support for primitive multipoints via a symbol code that starts with BS or BBS. Is there any documentation on what is allowable (valid codes)?

**Comment by mdeutch3** [comment]
BS shapes are generic shapes with fill and text (T modifier). BBS shapes are buffered shapes which take AM[0] as the size of the buffer in meters. They also take the T modifier

**Comment by spyhunter99** [comment]
ok thanks

**Comment by michael-spinelli** [comment]
They're defined at the top of the symbolconstants.xml.  I'll have to add some documentation.

[symbolconstants](https://github.com/missioncommand/mil-sym-android/blob/master/Renderer/res/raw/symbolconstantsc.xml#L15)
