### ISSUE TITLE
Maven build?

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#32]
Would guys be willing to accept a maven based build conversion? Technically, you should be releasing an AAR artifact for android, since we relying some of the resource files being present

**Comment by michael-spinelli** [comment]
Yes.  I've wanted to look into switching to Android Studio but haven't had the time.

**Comment by michael-spinelli** [comment]
Thanks for doing this!  Merge done.

**Comment by spyhunter99** [comment]
No problem.  Now about adding unit tests. ... lol
