### ISSUE TITLE
Swept Area preview is different than render

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#33]
The Swept Area's preview is a purple like color, however it renders as a light, off white color.

**Comment by mdeutch3** [comment]
It renders as pink dots on a white background.
![swept_area](https://cloud.githubusercontent.com/assets/5973557/8942659/9c2f64ec-3544-11e5-912b-36a57acd8dfe.png)

**Comment by michael-spinelli** [comment]
Small text at the bottom of page 956 (962 in the 2525C pdf) seems to imply it should be a transparent area with pink dots.

**Comment by spyhunter99** [comment]
I know what it's supposed to look like, however it's rendering differently over here. Could be an issues with osm bonus pack. I'll look into it further

**Comment by mdeutch3** [comment]
The image has been made transparent and the change was checked into GitHub. I'll make the other images transparent as required.
![xparent swept area](https://cloud.githubusercontent.com/assets/5973557/8944072/55745636-354c-11e5-9618-5513c4155489.png)

**Comment by mdeutch3** [comment]
Note: the above comment applies to the 8 multipoint METOC symbols with image fill.

**Comment by spyhunter99** [comment]
The multipoint was rendering as an empty polygon with a peach colored
border.  Not sure we are taking the same thing

**Comment by mdeutch3** [comment]
Swept Area: WO-DL-SA----A--. I'm talking about the render only, not about preview.

**Comment by spyhunter99** [comment]
in my case the preview looks ok, but the render is wrong. I'll dive into when i have time. It's possible the kml is jacked up or not being interpreted correctly

**Comment by spyhunter99** [comment]
milstd2525basecode WO-DL-SA----A--
milstd2525attributes {12=12, 15=false}
render multipoint KML with  attrib:2 mods:0 font:14 id=ebb187f2-7b79-451d-9694-5df4e4265c13 name=N/A code=WO-DL-SA----A-- points=-76.424503,39.567521 -76.424503,39.563617 -76.41695,39.554287 -76.393604,39.551574 -76.386566,39.556934 -76.38236,39.560507 -76.380472,39.562691 -76.424503,39.567521  altmode=relativeToGround scale=13255.0 bbox=-76.494626,39.514039,-76.2749,39.619904

<Folder id="ebb187f2-7b79-451d-9694-5df4e4265c13"><name><![CDATA[N/A]]></name><visibility>1</visibility><Placemark><description><![CDATA[<b>N/A</b><br/> Swept Area]]></description><Style id="lineColor"><LineStyle><color>ffdcf5f5</color><colorMode>normal</colorMode><width>12</width></LineStyle></Style><MultiGeometry><LineString><tessellate>1</tessellate><altitudeMode>clampToGround</altitudeMode><coordinates>-76.42468162,39.5676049 -76.42468553,39.56371209 -76.41702219,39.55440319 -76.39378881,39.55169514 -76.38676593,39.55694198 -76.38237537,39.56066554 -76.38061813,39.56269657 -76.42468162,39.5676049 </coordinates></LineString></MultiGeometry></Placemark></Folder> 


looks like a kml issue. Only a line was sent back.

**Comment by mdeutch3** [comment]
We currently have no KML support for the METOC image fills for the Android version. Even the Java version does not have that fully implemented. And the Java version uses Tomcat as the image fill server. To my knowledge we're not using Tomcat in conjunction with Android renderer.

**Comment by spyhunter99** [comment]
well, that would do it. I found a project called Nano http that's a mini android based web server, maybe we can rig that in and only bind to localhost in order to serve up the anchor points. Nano also works on straight jdk so it can be used in both places. Not sure what the priority is on this but it's a potential solution
https://github.com/NanoHttpd/nanohttpd

**Comment by mdeutch3** [comment]
Our app is writing a KML string, not accessing the server, so it should not matter. Google Earth would access the server with the call from the KML when displaying it. Deploying our server (mil-sym-service) is described in Mil Symbology Web Service Developer's Guide, accessible from https://github.com/missioncommand/mil-sym-java, although I'm not sure if it mentions the required modifier symbolFillIds. I believe we've only ever deployed with Tomcat.
Android renderer should be able to produce the KML that Java renderer is doing, even if Swept Area is not yet supported. I'm looking into this. I know mil-sym-service supports Foul Ground, Kelp and maybe some other multipoint METOC's.

**Comment by mdeutch3** [comment]
Changes to the renderer and tester have been checked in. As far as I can tell it only supports Kelp and Foul Ground for the METOC's. You can try oil/gas rig symbol code but the fill will look different than the mil-std. The symbol fill id is added to the Sparse array as shown in the utility class.
        if(!symbolFillIds.isEmpty())
            modifiers.put(ModifiersTG.SYMBOL_FILL_IDS, symbolFillIds);
where symbolFillIds is the 15 character symbol code for the single point to be used for fill, e.g. WOS-HHDF--P---- for Foul Ground.
So it should include the pattern fill in the KML that is generated at runtime. Save the file using adb pull storage/sdcard/temp.kml, etc.. Then if mil-sym-service is deployed with Tomcat, start Tomcat. The fill should display with the symbol if you open the KML file in Google Earth or whatever KML viewer you're using.

**Comment by michael-spinelli** [comment]
I'm going to have to do some work to automate that for METOCs.  The user shouldn't have to specify the symbolFillID.

**Comment by mdeutch3** [comment]
Also an issue is the image fill doesn't clip with the symbol because the tgPoints are not clipped. I've got to do some work on that. For JavaScript version it might clip.

**Comment by mdeutch3** [comment]
The clipping issue was fixed for METOC fills and code checked in. The METOC fills now clip for all versions.

**Comment by michael-spinelli** [comment]
pattern fills updated in latest release:
https://github.com/missioncommand/mil-sym-android/releases/tag/v0.1.32
