### ISSUE TITLE
Single point echelon field isn't centered within task group frame

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#4]
I noticed that both the android and jdk version have this issue. The echelon decorator isn't centered within the taskforce/group frame. Can this be fixed? it's more of an aesthetics thing. Thanks!

**Comment by michael-spinelli** [comment]
Fixed in Android.  I'd like to see a screenshot of the jdk version.  I'm not seeing the same issue there.

**Comment by spyhunter99** [comment]
ok ahea and close. i thought i saw the same issue but i guess i was mistaken. thanks for the quick turn around
