### ISSUE TITLE
Support for gradle publication and additional checks

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#44]
in what little spare time i have, i've been working with a friend on gradle-fury. basically it's a bunch of helper scripts for gradle to make publishing possible to maven central. As an added bonus, we figured out how to run a bunch of code checks with gradle and the equivalent of the maven site plugin. If interested, I can ope a pull request for this. It'll make your job easier in terms of release management too.

**Comment by michael-spinelli** [comment]
We will be posting the java and android ports to bintray:
https://bintray.com/missioncommand/maven/mil-sym-android#
https://bintray.com/missioncommand/maven/mil-sym-java#
