### ISSUE TITLE
Error when importing Renderer using JitPack.io

### ISSUE THREAD

**Issue by Sufaev** [missioncommand/mil-sym-android#48]
Hello!

I am trying to import your library in Android Studio using JitPack.io repository, which can download releases from GitHub.

Here is how it should be https://jitpack.io/#missioncommand/mil-sym-android/v0.1.17

Step 1. Add JitPack into your root build.gradle at the end of repositories:

	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}

Step 2. Add the dependency to your project

	dependencies {
	        compile 'com.github.missioncommand:mil-sym-android:v0.1.17'
	        or
	        compile 'com.github.missioncommand.mil-sym-android:Renderer:v0.1.17'
	}

But when i try to build, Gradle tells me:
Error:Could not find Renderer.aar (com.github.missioncommand:mil-sym-android:v0.1.17).
Searched in the following locations:
    https://jitpack.io/com/github/missioncommand/mil-sym-android/Renderer/v0.1.17/Renderer-v0.1.17.aar

The library in your release named mil-sym-android-renderer-0.1.17.aar.

Is it a problem in some Maven configuration in your project on GitHub or it is a JitPack mistake?

Is there any other way to import renderer via repository?

Thanks.

**Comment by Sufaev** [comment]
If you look into build log of JitPack https://jitpack.io/com/github/missioncommand/mil-sym-android/v0.1.17/build.log you will found that it creates file Renderer-v0.1.17-debug.aar instead of Renderer-v0.1.17.aar thats why import does not work.

Is it possible to fix somehow in your GitHub project side or it is a JitPack error, what do you think?

**Comment by Sufaev** [comment]
Possibly it is due too:

WARN You're perform a release build with android artifacts but have not specified signing certificate (JKS). Check gradle.properties

**Comment by spyhunter99** [comment]
see issue #44 there is a plan to publish to maven central via sonatype oss but it think there were some open questions internally on it as well as what the groupId would need to be to meet sonatype's requirements. 

As such, you have two options

1) change your build file to include the release/debug classifier
`compile 'com.github.missioncommand.mil-sym-android:Renderer:debug:v0.1.17'`
2) git submodule or git clone this project then run `gradlew install` then reference it through the repository mavenLocal via the defined pom settings in `gradle.properties` which is currently `mil.army.us.peoc3t.milsym:Renderer:0.0.65-SNAPSHOT:debug`

@michael-spinelli looks like the version numbers in the gradle.properties are not in sync with the release tags

**Comment by Sufaev** [comment]
Error:(31, 13) Failed to resolve: com.github.missioncommand.mil-sym-android:Renderer:debug

I have tried:
compile 'com.github.missioncommand.mil-sym-android:Renderer:v0.1.17@debug'
It sync with gradle without error but does not see classes from aar.

Could you help me to find a way how to connect renderer without manually download of aar file from GitHub and importing it locally as a module?

**Comment by michael-spinelli** [comment]
I'll update gradle.properties

**Comment by Sufaev** [comment]
Will it fix JitPack compatibility?

27 січ. 2017 р. 16:59 "Michael Spinelli" <notifications@github.com> пише:

**Comment by michael-spinelli** [comment]
I'm not sure.  I think spyhunter was just letting me know the number were out of sync.

**Comment by spyhunter99** [comment]
whoops typo, try this

`compile 'com.github.missioncommand.mil-sym-android:Renderer:v0.1.17:debug'`

**Comment by Sufaev** [comment]
Spyhunter, what do you think why JitPack do not make release AAR file? Is
it beacause some signature configuration missed (according to build log)?

What should be chaged in Git repositary to solve the problem described in
current topic?


27 січ. 2017 р. 7:06 PM "spyhunter99" <notifications@github.com> пише:

whoops typo, try this

compile 'com.github.missioncommand.mil-sym-android:Renderer:v0.1.17:debug'

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/missioncommand/mil-sym-android/issues/48#issuecomment-275717752>,
or mute the thread

**Comment by spyhunter99** [comment]
because no one in their right mind checks in their private signing key and password into version control. And because gradle-fury will only do a "release" build if the version number does not contain the text "SNAPSHOT" and if the signing key is available. A 'SNAPSHOT' build is not a release build.

**Comment by Sufaev** [comment]
Do you mean that all other libraries which I use in my project via JitPack
have private key in repository?

For example, I have included NASAWorldWindAndroid in the same way without
problems.

27 січ. 2017 р. 8:38 PM "spyhunter99" <notifications@github.com> пише:

**Comment by Sufaev** [comment]
This link works:
compile 'com.github.missioncommand.mil-sym-android:Renderer:v0.1.17:debug@aar'

But anyway I do not understand how all other repositories work without debug addition.

**Comment by michael-spinelli** [comment]
We will be posting the java and android ports to bintray:
https://bintray.com/missioncommand/maven/mil-sym-android#
https://bintray.com/missioncommand/maven/mil-sym-java#

We've changed the groupID

mil.army.missioncommand:mil-sym-android-renderer:0.1.21
