### ISSUE TITLE
Problem with clipping

### ISSUE THREAD

**Issue by Sufaev** [missioncommand/mil-sym-android#49]
Hello.

A am doing tile based tactical graphic rendering for 3d map engine. To make this, I am splitting tactical graphics on square tiles depending on zoom and render each part applying clipping area.

But, when I am applying clipping rectangle to multipoint tactical graphics, renderer generate additional shapes along the clipping area perimeter and my tactical graphics looks like invalid, splitted on many visual squares.

How to avoid this effect? What am I doing wrong? Is it a bug?

**Comment by Sufaev** [comment]
Here is what i receive:
![screenshot_2017-02-19-20-42-10](https://cloud.githubusercontent.com/assets/12487306/23105280/86f8f3ea-f6e5-11e6-9f18-a63562746407.png)

Here is what i want to receive:
![screenshot_2017-02-19-20-52-06](https://cloud.githubusercontent.com/assets/12487306/23105284/92b269e6-f6e5-11e6-967f-a6952155af40.png)

**Comment by mdeutch3** [comment]
It's not a bug. There can be an extra line along the clipping edge or a little past it. The renderer assumes the clipped edge is outside the viewable area so it should not matter. The purpose of clipping is to prevent the renderer from having to calculate thousands of glyphs which are outside the viewable area When panning you can sometimes see the lines that had been outside the viewable area before the refresh is complete.

**Comment by Sufaev** [comment]
Ok. In this case what is the correct aproach to render symbols in 3D GIS when camera can view along the horizon and clippi g area is too big?

**Comment by mdeutch3** [comment]
The renderer has no knowledge of a camera and builds its own geo-to-pixels converter internally to be able to calculate the points for the graphic.
@michael-spinelli Would it be feasible to add a function with a converter parameter for Android?
if we did this it would accept a client-side converter which would need to implement IPointConversion. I don't know if this would work for you. We did something like this in JavaScript renderer for the Cesium client. I don't know if this would work for you. And we can't troubleshoot problems with client converter.

**Comment by Sufaev** [comment]
You probably missunderstand the prombem.
We are using directly clsRenderer.renderWithPolylines to obtain shapes according to symbol code, modifiers, scale and clip area. 

Scale is a real map scale which is calculated from camera altitude and screen dpi.

When I pass all parameters without clipping I may receive milion of points in shape.

How do you propose to use clipping in 3d gis, when there is no square clipping area like in 2d?

**Comment by mdeutch3** [comment]
Is there a polygonal clipping region? Years ago we tested a 2d polygon clip area with our clipping algorithm but no one has run with that.

**Comment by Sufaev** [comment]
I have clipping region in GIS (I use WorldWind) but when I look into horisont this region is too big.

To use your library in 3D it is required to split graphics on tikes with differend level of derails depending on disrance, but current clipping algorythm does not allow this.

Can you propose any other solutiona.

**Comment by mdeutch3** [comment]
If you're calling renderWithPolylines then you must be passing your own converter? So the converter is generating pixel values that are so large that the renderer is calculating millions of points? Is there a reason you can't use RenderSymbol so it can calculate the converter internally?
@michael-spinelli do you have any ideas?

**Comment by Sufaev** [comment]
No, the reason is not in a big clipping area. The reason is in a big Scale value when you look at map from small distance.

I am using real map scale calculated as virtual viewport screen size in meters devised to real android sceen size in meters.

When I am looking on map in 1:10 000 scale it generates many details of symbol.

**Comment by michael-spinelli** [comment]
We are looking at options to make this work better.

**Comment by michael-spinelli** [comment]
Added support for a polygonal bounding bbox. Pass in a space delimited string: x,y[sp]x,y[sp] ... Not limited to 4 points. Assumes points are clockwise.

**Comment by mdeutch3** [comment]
I can solve the problem by using some big scale, but then symbol will be drawn not according to stanag.
The renderer has a function that computes a reasonable scale based on the extents it was passed. If the original scale varies outside of the minimum to maximum range it computes then it assigns one or the other value to the scale. So to know what scale the renderer is actually using we would need the data you are passing and we would step into it.

**Comment by Sufaev** [comment]
I solved the problem like described in the last mdeuch3 post.

When user looks on the map in 2d mode program use real map scale and clipping based on screen extent.
Wnen user looks on the earth in 3d program calculates diagonal size of symbol in meters and use a limit of maximum 5000dp and calculates minimum meters per dp scale for current size in meters.

So the problem is partially solved, but too pity that the level of details is growing.

You may close this task.
