### ISSUE TITLE
App crash when rendering multipoint GFMPOGZ-------X (mobility obstacle)

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#5]
Not sure what's happening in, probably trying to load a wrong resource or something

font size:18 
id=6d518653-e644-4ca9-88fc-834b6f7f7a57 
name="a name" 
description="description"
 code=GFMPOGZ-------X points=-100.40499237112768,33.80812615466675 -100.57388432358725,33.58973454477413 -100.83305865544072,33.79939549389823 -100.68745451099262,33.94208534428098 altmode=relativeToGround scale=0.4121233846596544 bbox=null
 Quantity 0
 Direction of movement 0
 DTG 1969-12-31T19:00:00-0500
 DTG 1969-12-31T19:00:00-0500
 Altitude or depth 0

BRAND=google, PRODUCT=razorg, TOTAL_MEM_SIZE=28361302016, AVAILABLE_MEM_SIZE=13396865024, CUSTOM_DATA=, STACK_TRACE=java.lang.OutOfMemoryError: Failed to allocate a 2078813228 byte allocation with 7228576 free bytes
  at armyc2.c2sd.JavaLineArray.arraysupport.GetLineArray2(arraysupport.java:80)
  at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer2.GetLineArray(clsRenderer2.java:315)
  at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer.render_GE(clsRenderer.java:1053)
  at armyc2.c2sd.JavaRendererServer.RenderMultipoints.clsRenderer.renderWithPolylines(clsRenderer.java:865)
  at sec.web.render.MultiPointHandler.RenderSymbol(MultiPointHandler.java:682)
  at sec.web.render.SECWebRenderer.RenderSymbol(SECWebRenderer.java:320)

**Comment by michael-spinelli** [comment]
At first glance I'd say your [scale](https://github.com/missioncommand/mil-sym-android/wiki#3316-scale-for-3d) is way too small. It shouldn't be less than zero.
from the [dev docs](https://github.com/missioncommand/mil-sym-android/wiki#3316-scale-for-3d)
3.3.1.6 SCALE (FOR 3D)

scale = a number corresponding to how many meters one meter of our map represents. A value "50000" would mean 1:50K which means for every meter of our map it represents 50000 meters of real world distance.

**Comment by mdeutch3** [comment]
If the bbox is not null and is reasonable then the renderer calculates a reasonable value for the scale to use in case an unreasonable scale is passed. But if the bbox is null and the scale is unreasonable then the resultant pixels will be unreasonable, in this case much too large, which caused the out of memory error when it tried to calculate the glyphs. If you're not going to pass a reasonable scale then please set the bbox with reasonable extents.

**Comment by spyhunter99** [comment]
I think my calculation is meters per pixel. I've changed to km/inch of screen and i'm at least getting the graphics to render now. thanks for the clarification
