### ISSUE TITLE
SYMBOL MODIFIER (POSITION 11, 12) not draw

### ISSUE THREAD

**Issue by elile** [missioncommand/mil-sym-android#59]
Hi, 
I'm trying to draw SPAPMFB---EK--- symbol but as you can see the  SYMBOL MODIFIER won't draw.

![spapmfb---ek---](https://user-images.githubusercontent.com/2623678/27397675-cc243602-56bf-11e7-88bf-5ce7aa3a2744.png)

**Comment by michael-spinelli** [comment]
My understanding is that echelons only apply to ground units.
