### ISSUE TITLE
E*NPCE----***** fails to render

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#6]
This fails on both the JDK and ADK versions.

ADK fails with the error 
attempt to invoke virtual method 'int armyc2.c2sd.renderer.utilities.SinglePointLookupInfo.getWidth()' on a null object reference
armyc3.c2sd.renderer.utilities.SymbolDimensions.getSymbolBounds (line 167)
called from SinglePointRenderer.RenderSP line 636
from MilStdIconRenderer.java line 310

**Comment by michael-spinelli** [comment]
It IS a 2525C symbol so make sure you're setting the symbology standard properly.  There was an issue with the JDK version handling bad codes (2525C code with the renderer set to 2525B).  I will be making a fix for that but if the symbolog standard is properly set to 2525C, it should render.  At least that's what I'm seeing on my side.

**Comment by spyhunter99** [comment]
on ADK, this causes another issue, which I found. Line 132 of SinglePointRenderer, change modifiers.get to attributes.get.

on JDK, i'm using an older version 0.0.35 so that may be the problem. i'll upgrade and try it again

**Comment by michael-spinelli** [comment]
good catch.  I'll fix that and I'll be making a change to android to better handle bad codes.

**Comment by spyhunter99** [comment]
on ADK, 2525c icons are now rendered correctly with that small fix. i'm good to close once that's patched

**Comment by michael-spinelli** [comment]
pushed fix for symbology standard check and improved handing for unrecognized codes.
