### ISSUE TITLE
Alternate symbols for operational condition modifiers for tactical symbols

### ISSUE THREAD

**Issue by elile** [missioncommand/mil-sym-android#60]
![image](https://user-images.githubusercontent.com/2623678/27628282-37cad71c-5bf7-11e7-959b-8c2cbd647052.png)

Hi, 
Can I draw the operational condition status only with the Alternate mode or there is a switch to draw black statuses on it (for example black X, destroyed).
As describe in the PDF TABLE III-1 VS TABLE III-2.
**My goal is to draw colored symbol with black statuses on it if possible**
Thanks

**Comment by michael-spinelli** [comment]
This will be in the next release:
-Added RendererSettings.getInstance().setOperationalConditionModifierType  (i.e. RendererSettings.OperationalConditionModifiierType_SLASH or RendererSettings.OperationalConditionModifiierType_BAR)

If not tomorrow, later next week.

**Comment by elile** [comment]
Thank you

**Comment by elile** [comment]
![image](https://user-images.githubusercontent.com/2623678/27859846-c9258456-6182-11e7-9ec4-7c409f516a66.png)

Hi, you don't implement the full options for the operational condition, the DAMAGED slash don't drawn. 
The operational conditions slashes need to be the same as the TABLE III-2(shown in the image),
green = no slashes
yellow = one slashes
red = two slashes (X)

**Comment by michael-spinelli** [comment]
I saw it work before but I tried again and you're right.  I'll check what happened.

**Comment by michael-spinelli** [comment]
ok, it was a bug I had fixed earlier in java and javascript but forgot to bring into android.  I'll have a new release today.

**Comment by michael-spinelli** [comment]
fixed in release v0.1.30
