### ISSUE TITLE
Slash Operational Condition Indicator Modifier

### ISSUE THREAD

**Issue by elile** [missioncommand/mil-sym-android#62]
Hi,
I need to set different color of the **slash** operational condition modifier rather than black,
Can you add this ability?
Thanks

**Comment by michael-spinelli** [comment]
Any arbitrary color or the color that the equivalent bar version of the operational condition modifier would use?  Either way we're getting beyond what is defined in the MilStd.

**Comment by elile** [comment]
Actually we need the slash in red color for all the operational condition, but if will be the ability to change to arbitrary color it will help to us and everybody

**Comment by michael-spinelli** [comment]
I don't know what your interoperability requirements are but that arbitrary color won't carry over to any other system unless they're intentionally doing to same thing.  Then you have the issue of it looking different between systems.

**Comment by michael-spinelli** [comment]
Would this be consistent across symbols or many graphics with potentially different colored slashes?

**Comment by michael-spinelli** [comment]
No response from elile and no plans to implement
