### ISSUE TITLE
Missing opening tag in XML

### ISSUE THREAD

**Issue by joerandazzo84** [missioncommand/mil-sym-android#63]
There is a missing opening tag on line 253 in tacticalgraphics.xml. This causes an issue when proguard validates the xml.

`
</SYMBOL>
    <SYMBOLID>G*G*AAF---2525C</SYMBOLID>
    <MAPPING>2052</MAPPING>
    <DESCRIPTION>Tactical Graphics_Command And Control And General Maneuver_Aviation_Areas_SHORT-RANGE_AIR_DEFENSE_ENGAGEMENT_ZONE (SHORADEZ)</DESCRIPTION>
  </SYMBOL>
  <SYMBOL>`

**Comment by michael-spinelli** [comment]
Fixed, you'll see it in the next release

**Comment by michael-spinelli** [comment]
v0.1.31
