### ISSUE TITLE
Hostile battle position  symbol has an excessive amount of ENY labels.

### ISSUE THREAD

**Issue by alberto-acevedo** [missioncommand/mil-sym-android#67]
During testing of the MMC (Smart Client), it was identified that for the hostile version of the  Battle Position symbol that it had an excessive amount of ENY labels.

**Comment by alberto-acevedo** [comment]
The behavior is expected and it is by design. I enhanced the reindeer by adding an option to display ENY labels in all segments, or to only display the label 2 times, one in the north and the other one in the south of the hostile graphics that disply ENY.

**Comment by michael-spinelli** [comment]
fixed in release v0.1.36
