### ISSUE TITLE
Limit of Advance (LOA) and Line of Departure (LD) symbols have T modifier text to the side

### ISSUE THREAD

**Issue by michaeltk3** [missioncommand/mil-sym-android#69]
The T modifier text for the LOA and LD symbols are not directly under the LOA/LD text but rather to the side. See screen shoot.
![image](https://user-images.githubusercontent.com/32075980/32898523-61bb3f70-cab6-11e7-8c20-6a775e69b90c.png)
![image](https://user-images.githubusercontent.com/32075980/32898777-1cbb2db2-cab7-11e7-95dc-5b518e7b6203.png)

**Comment by rsupnekar** [comment]
Here's what the change to justify looks like, using CENTER instead of LEFT or RIGHT

![screenshot from 2017-11-20 10-52-18](https://user-images.githubusercontent.com/25460036/33027425-0e1b6a60-cde1-11e7-895d-0f2bcbc70b06.png)

**Comment by michael-spinelli** [comment]
Hmm, looked better than that in our tester.  I'll take another look.

**Comment by michael-spinelli** [comment]
Does the tester you took the screenshot from redraw the symbol when the scale changes?

**Comment by michael-spinelli** [comment]
stale, closing
