### ISSUE TITLE
SymbolUtilities.canSymbolHaveModifier() always returns true for undefined modifiers

### ISSUE THREAD

**Issue by rjl6d** [missioncommand/mil-sym-android#70]
SymbolUtilities.canSymbolHaveModifier() will always return true for modifiers that are not valid for any tactical graphic. This is because ModifiersTG.getModifierLetterCode() returns an empty string by default which causes the check to always return true.

For example, when checking if Area Target (`G*F*AT----****X`) has a speed modifier, the function canSymbolHaveModifier() will return true.

**Comment by michael-spinelli** [comment]
fixed in release v0.1.36
