### ISSUE TITLE
No image returned for ICE DRIFT (DIRECTION) symbol from MilStdIconRenderer

### ISSUE THREAD

**Issue by michaeltk3** [missioncommand/mil-sym-android#76]
Using the following:

ImageInfo imageInfo = null;
final SparseArray<String> attributes = new SparseArray<>();
int symbolSize = (int) context.getResources().getDimension(R.dimen.symbol_size);
attributes.put(MilStdAttributes.PixelSize, Integer.toString(symbolSize));
final MilStdIconRenderer iconRenderer = MilStdIconRenderer.getInstance();
imageInfo = iconRenderer.RenderIcon(symbol.getCode(), new SparseArray<String>(), attributes);

results in imageInfo.getImage() returning null.

This is the ICE DRIFT (DIRECTION) symbol from the METOC group.

This isn't critical but wanted to make you aware.

**Comment by michael-spinelli** [comment]
OK, looking at where it is in the MilStd, the symbol code must be a mistake.
WO-DIDID---L--- implies a multipoint line.  but every other graphic in the same sub group is a single point and they all look similar.  I'm going to make a code WO-DIDID--P---- and have WO-DIDID---L--- render the same single point graphic.

**Comment by michael-spinelli** [comment]
I'm adding WO-DIDID--P----.  Both WO-DIDID--P---- and WO-DIDID---L--- will render the same singlepoint version.  I've emailed some people in the mean time to figure out what the actual intent was.  Although I'm pretty sure the single point version is what was intended.
