### ISSUE TITLE
NPE when rendering icons

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#8]
I'm running into a few NPE's when rendering a number of the 'G' graphics. All of the NPEs are at
armyc2.c2sd.renderer.utilities.TextInto.<init>(line 17), attempting to invoke java.lang.String() on a null object reference.

I'm not entirely sure what I'm missing in the modifiers, but this probably shouldn't be throwing up like this either ;)

Here's the codes in question

GFSPPAT-------X
GFGPDPOF------X

**Comment by spyhunter99** [comment]
I think the problem is that had null passed for an AdditionInfo1-3 field. I threw in some additional null checks on my end and all was fixed

**Comment by michael-spinelli** [comment]
Yeah, I can see how that could happen.  I'll make things a little more robust in the next release.

**Comment by michael-spinelli** [comment]
fixed in release .56
