### ISSUE TITLE
SymbolDefTable.getSymbolDef for S*F*UCI---***** returns a null value for both standard sets

### ISSUE THREAD

**Issue by spyhunter99** [missioncommand/mil-sym-android#9]
Trying to call the above mentioned code as defined in the wiki guide. It looks like the referenced code isn't in the hashmap.

**Comment by michael-spinelli** [comment]
Did you mean "S*G*UCI---*****" ?

I looked for "S*F*UCI---*****" in 2525 B & C and didn't see it.  So it wouldn't be in the hash.

**Comment by spyhunter99** [comment]
sorry typed it wrong
S*G*UCI---*****

**Comment by spyhunter99** [comment]
S * G * UCI---*****

**Comment by michael-spinelli** [comment]
Oh, right.  This is probably is a little unintuitive.  SymbolDefTable holds SymbolDefs for Tactical Graphics (starts with 'G') and METOCs (starts with 'W').

UnitDefTable holds UnitDef objects for everything else.

**Comment by spyhunter99** [comment]
Ok gotcha. The functionality we're looking for is to know what selection of modifiers apply to a given symbol code so that the user can be presented with a list of fields to fill in based on icon selection. I.E. SymbolDef.getModifiers(). Is this type of functionality present elsewhere and we're just looking in the wrong spot?

**Comment by michael-spinelli** [comment]
We don't have something that lists them out for units like it does for tactical graphics in SymbolDef.  What we do have is SymbolUtilities.hasModifier().

Given a symbolID, modifierConstant and SymbologyStandard, this will let you know if a symbol has the modifier in question.  

 /**
*
* @param symbolID
* @param modifier - from the constants ModifiersUnits or ModifiersTG
* @param symStd - 0=2525B, 1=2525C. Constants available in
* RendererSettings.
* @return
*/
public static
Boolean hasModifier(String symbolID, int modifier, int symStd)

Outside of the that, there's table IV in 2525C which gives you a break down.  
Modifiers for units don't vary like they do for tactical graphics.  For units you can make the assumption that a group of units (like Signals Intelligence) will have a certain set of modifiers.

**Comment by spyhunter99** [comment]
Ok just so I'm clear, this file:
https://github.com/missioncommand/mil-sym-android/blob/master/Renderer/src/armyc2/c2sd/renderer/utilities/ModifiersUnits.java

Applies to everything but "W" and "G" symbol codes.

"W" and "G" symbol codes use the following (and usage varies based on the symbol code):
https://github.com/missioncommand/mil-sym-android/blob/master/Renderer/src/armyc2/c2sd/renderer/utilities/ModifiersTG.java


is that accurate?

**Comment by michael-spinelli** [comment]
yes

**Comment by spyhunter99** [comment]
thanks for the quick response. i appreciate it

**Comment by michael-spinelli** [comment]
no problem.
