### ISSUE TITLE
No ModifiersUnits.getModifierLetterCode() method

### ISSUE THREAD

**Issue by Sufaev** [missioncommand/mil-sym-android#90]
Hello.

ModifiersUnits has no possibility to convert Integer codes to standard string letter codes and back as it is possible by ModifiersTG.

Could you please implement getModifierLetterCode() and getModifierKey() methods for ModifiersUnits the same as for ModifiersTG.

It is now not possible to iterate on Modifiers returning their standard MilStd2525 string code.

**Comment by michael-spinelli** [comment]
will be in v0.1.45
