### ISSUE TITLE
Why ModifiersTG.getModifierLetterCode has commented modifier A_SYMBOL_ICON?

### ISSUE THREAD

**Issue by Sufaev** [missioncommand/mil-sym-android#92]
Why ModifiersTG.getModifierLetterCode and getModifierName has commented modifier A_SYMBOL_ICON?
Is this restriction having some business logic?
If yes, then why  ModifiersUnits.getModifierLetterCode has not commented A_SYMBOL_ICON?

If this restriction is obsolete, I prefer to have A_SYMBOL_ICON in ModifiersTG.getModifierLetterCode add getModifierName just to have general way to map any valid modifier to number and backward, even if it is graphical.

```
public static String getModifierLetterCode(int modifier) {
        switch (modifier) {
            //case A_SYMBOL_ICON:
            //    return "Symbol Icon";
```

The same question is about
```
 //case S_OFFSET_INDICATOR:
 //    return "Offset Indicator";
```

I can understant that A, B and S modifiers are excluded from GetModifierList() as they are not textual, but why not to have them in mapping?

**Comment by michael-spinelli** [comment]
I guess they could be uncommented.  I think the original concern was that people would attempt to "add" these modifiers when they feed off of the symbol code and aren't something that is passed in separately.
