### ISSUE TITLE
Rectangle2D.java contains calculation bug?

### ISSUE THREAD

**Issue by wns1** [missioncommand/mil-sym-android#93]
The "contains" method for Point2D in Rectangle2D.java currently looks like this:
```
    public boolean contains(Point2D pt)
    {
        if(x<=pt.getX() && pt.getX()<=x+width)
            if(y<=pt.getY() && pt.getY()<=x+height)
                return true;
        
        return false;
    }
```
The second if statment compares the y value of pt with **x** value plus height instead of **y**. Seems to be a copy paste issue.

Same found for "contains" method for double x y values. There it's **y + width** instead of **y + height**. Isn't it?
```
    public boolean contains(double x1, double y1)
    {
        if(x<=x1 && x1<=x+width  && 
                y<=y1 && y1<=y+width)
            return true;
        else return false;
    }
```

**Comment by michael-spinelli** [comment]
Looks like both functions are wrong. x=height in the top one isn't right either.
Thanks for the catch.

**Comment by michael-spinelli** [comment]
forgot to close
